server:
  port: 80

appSetting:
  jwt:
    expire: 20
    secret: f93a2dd3-657a-4c21-9d5c-0d5ca1b538f9

spring:
  datasource:
    url: jdbc:mysql://47.100.229.56:3306/raccoon?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    username: root
    password: Mk;c6[cB424n

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true